# Generated by Django 4.1.4 on 2023-01-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_location'),
        ('project', '0003_review_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
