# Generated by Django 4.1.4 on 2023-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='a',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
