# Generated by Django 4.1.4 on 2023-01-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='a',
        ),
    ]
