# Generated by Django 4.1.4 on 2023-01-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=500)),
                ('short_intro', models.CharField(max_length=250)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='default_profile.png', upload_to='profiles')),
                ('social_github', models.CharField(blank=True, max_length=500, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('social_linkdedin', models.CharField(blank=True, max_length=500, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=500, null=True)),
                ('social_website', models.CharField(blank=True, max_length=500, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
