# Generated by Django 4.1.4 on 2023-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
