# Generated by Django 4.1.4 on 2023-01-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_skill_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_linkdedin',
            new_name='social_linkedin',
        ),
    ]
