# Generated by Django 4.1.4 on 2023-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_message_options_alter_message_receiver'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver'))), name='check_sender_reciever_same_message'),
        ),
    ]
