# Generated by Django 4.1.4 on 2023-01-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_message_check_sender_reciever_same_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='check_sender_reciever_same_message',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('receiver')), _negated=True), name='check_sender_reciever_same_message'),
        ),
    ]
