# Generated by Django 4.1.4 on 2023-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_social_linkdedin_profile_social_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_stackoverflow',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
